services:
  mongo:
    image: mongo:7
    volumes: [ "mongo-data:/data/db" ]
    ports: [ "27017:27017" ]

  backend:
    build: ./backend
    env_file: [.env]
    volumes: [ "./backend:/code" ]
    ports: [ "8000:8000" ]
    depends_on: [ mongo ]
    dns:
      - 8.8.8.8
      - 8.8.4.4
  
  frontend:
    build: ./frontend
    env_file: [.env]
    volumes: [ "./frontend:/app" ]
    ports: [ "3000:3000" ]
    depends_on: [ backend ]
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  mongo-data: 